class ExceptionFinallyFunction
{
 public static void main(String args[])
 {
  try
  {
   System.out.println("Try Block");
  }catch()
  {
   System.out.println("Catch Block");
  }
  finally
  {
   System.out.println("Finally Block");
  }
 }
}